package config

import "slices"

// legacyDefaultExecuteGroupBlacklist returns the pattern list that the
// pre-rename `security.groups.execute.blacklist` key shipped as its default.
// The app no longer seeds any predefined patterns — security.groups.execute.
// blocklist is empty by default and purely user-authored — so this list
// exists ONLY for the one-time load migration: it lets the loader recognize
// a legacy list that is exactly the old shipped default and drop it (the
// effective blocklist is empty either way), while a customized legacy list
// is carried over to blocklist. Never use it for anything else; it is frozen
// history, not a living default.
func legacyDefaultExecuteGroupBlacklist() []string {
	return []string{
		"rm\\s+-rf\\s+/",
		"mkfs",
		"dd\\s+if=",
		"dd\\b[^|]*\\bof=/dev/(sd|hd|vd|xvd|nvme|mmcblk|loop|ram|zram|dm-|md|disk|mapper|mem|kmem|port)",
		">\\s*/dev/(sd|hd|vd|xvd|nvme|mmcblk|loop|ram|zram|dm-|md|disk|mapper|mem|kmem|port)",
		"\\b(shutdown|reboot|halt|poweroff|init\\s+[06])\\b",
		"\\b(curl|wget)\\b.*\\|\\s*(?:\\S*/)?(?:env\\s+)?\\b(sh|bash|zsh|dash|ksh|fish|perl\\d*|node|ruby|python[\\d.]*)\\b",
		">\\s*/etc/(passwd|shadow|sudoers|group|fstab)\\b",
		"(tee|dd)\\b[^|]*/etc/(passwd|shadow|sudoers)\\b",
		"\\bchmod\\b[^|]*\\b777\\b[^|]*/(etc|usr|boot|bin|sbin)\\b",
		">\\s*/boot/",
		":\\(\\)\\s*\\{",
		"\\bcrontab\\s+-r\\b",
		"\\b(iptables|ufw|nft)\\b[^|]*(-F\\b|--flush\\b|-X\\b|-P\\s+\\w+)",
		"sudo\\s+",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(mv|checkout|switch|restore)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(update-index|read-tree|checkout-index|mergetool|difftool|hook)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+add(\\s*($|[;&|)\\n])|\\s+(-[^\\s-]*[A-Za-mo-uw-z]|--(all|update|patch|interactive|force|edit|intent-to-add|chmod|renormalize|refresh|sparse|ignore-missing|ignore-removal|pathspec-from-file)\\b|--\\s|[^\\s;&|<>()\\x60-]))",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+rm(\\s*($|[;&|)\\n])|\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(-[^\\s-]*[frRF]|--(cached|force|recursive|ignore-unmatch|pathspec-from-file)\\b|--\\s|[^\\s;&|<>()\\x60-]))",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+clean\\s+(?:(?:[^\\s;&|()-][^\\s;&|()]*|-[^\\sn-][^\\sn]*|--(?:exclude|quiet|verbose)\\b(?:=[^\\s;&|()]+|\\s+[^\\s;&|()]+)?)\\s+)*(-[^\\s-]*[dDfFxXiI]|--(force|directory|interactive)\\b)",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+stash(\\s*($|[;&|)\\n])|\\s+(push|pop|apply|drop|clear|store|branch|create|save)\\b|\\s+-)",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+apply(\\s*($|[;&|)\\n])|\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(-[^\\s-]*[3R]|--(cached|index|3way|reverse|whitespace|exclude|include|directory|recount|build-fake-ancestor|allow-empty|inaccurate-eof|unsafe-paths|binary)\\b|--\\s|[^\\s;&|()\\x60-]))",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(commit|am|merge|rebase|revert|cherry-pick|replace|update-ref|symbolic-ref|bisect|filter-branch|filter-repo|fast-import)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+reset\\s+(-[^\\s-]+|--(hard|soft|mixed|keep|merge|patch|quiet|interactive|pathspec-from-file)\\b|\\S*[~^/]|[^;&|()]*\\s--(hard|soft|mixed|keep|merge|patch|quiet|interactive)\\b|[^\\s;&|<>()\\x60-]+[\"'\\x60]?\\s*($|[;&|\\n)]))",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+config\\s+((?:--[^\\s]+|--|-[fF]\\s+\\S+)\\s+)*(-[eE]\\b|--(unset(-all)?|add|replace-all|rename-section|remove-section|edit)\\b|[^-\\s]\\S*\\s+\\S)",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+notes\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose|--ref(=[^\\s]+|\\s+[^-\\s]\\S*)?)\\s+)*(add|append|copy|edit|prune|remove|merge)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+reflog\\s+(expire|delete)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+branch\\s+(-[^\\s-]*[dDfFmMcCtuU]|--(delete|move|copy|edit-description|set-upstream-to|unset-upstream|track|force|create-reflog)\\b|--\\s|[^\\s;&|<>()\\x60-])",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+tag\\s+(-[^\\s-]*[aAdDfFmsSuU]|--(delete|force|annotate|sign|local-user|edit|create-reflog)\\b|--\\s|[^\\s;&|<>()\\x60-])",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+remote\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(add|remove|rm|rename|set-url|set-head|set-branches|prune|update)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+submodule\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(add|init|deinit|update|set-url|set-branch|sync|absorbgitdirs|foreach)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+worktree\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(add|remove|prune|move|repair|lock|unlock)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+sparse-checkout\\s+(set|add|reapply|disable|init|cone|no-cone)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(clone|push|pull|send-email|imap-send|daemon|instaweb)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+bundle\\s+create\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(send-pack|upload-pack|receive-pack|shell|http-backend|upload-archive|http-push)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(init|gc|prune|maintenance|repack|pack-refs|pack-objects|update-server-info|multi-pack-index|for-each-repo|hash-object|write-tree|mktree|mktag|unpack-objects|index-pack|credential|rerere|backfill|p4|svn|lfs)\\b",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+archive\\s+[^;&|()]*\\s?(-o\\S*|--output\\S*)",
		"(^|[\\s;&|(\\x60]|[/\\\\])git(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+format-patch\\s+[^;&|()]*\\s?(-o\\S*|--output\\S*)",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])((sh|bash|zsh|dash|ksh|ksh93|mksh|yash|ash|csh|tcsh|fish)(\\.exe)?(\\s+-[a-z-]+(=[^\\s]+|\\s+[^-\\s]\\S*)?)*\\s+-[a-z]*c[a-z]*\\b|(powershell|pwsh)(\\.exe)?(\\s+-[a-z-]+(=[^\\s]+|\\s+[^-\\s]\\S*)?)*\\s+-(command|c)\\b|cmd(\\.exe)?(\\s+/[a-z:]+)*\\s+/[ck]\\b|\\beval\\b)[^;|\\n]*git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(mv|checkout|switch|restore|update-index|read-tree|checkout-index|mergetool|difftool|hook|commit|am|merge|rebase|revert|cherry-pick|replace|update-ref|symbolic-ref|bisect|filter-branch|filter-repo|fast-import|clone|push|pull|send-email|imap-send|daemon|instaweb|bundle\\s+create|send-pack|upload-pack|receive-pack|shell|http-backend|upload-archive|http-push|init|gc|prune|maintenance|repack|pack-refs|pack-objects|update-server-info|multi-pack-index|for-each-repo|hash-object|write-tree|mktree|mktag|unpack-objects|index-pack|credential|rerere|backfill|p4|svn|lfs|(reset|branch|tag|stash|remote|config|reflog|apply|clean|submodule|worktree|notes|add|rm|sparse-checkout)(\\s+-|\\s+[^\\s;&|()<>\\x60-]|[\"'\\x60]?\\s*($|[;&|\\n)])))",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])((python3?|node|perl|ruby|php)(\\.exe)?(\\s+-[a-z-]+(=[^\\s]+|\\s+[^-\\s]\\S*)?)*\\s+(-[cer]|--eval)\\b|\\b(iex|Invoke-Expression)\\b)[^|\\n]*git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(mv|checkout|switch|restore|update-index|read-tree|checkout-index|mergetool|difftool|hook|commit|am|merge|rebase|revert|cherry-pick|replace|update-ref|symbolic-ref|bisect|filter-branch|filter-repo|fast-import|clone|push|pull|send-email|imap-send|daemon|instaweb|bundle\\s+create|send-pack|upload-pack|receive-pack|shell|http-backend|upload-archive|http-push|init|gc|prune|maintenance|repack|pack-refs|pack-objects|update-server-info|multi-pack-index|for-each-repo|hash-object|write-tree|mktree|mktag|unpack-objects|index-pack|credential|rerere|backfill|p4|svn|lfs|(reset|branch|tag|stash|remote|config|reflog|apply|clean|submodule|worktree|notes|add|rm|sparse-checkout)(\\s+-|\\s+[^\\s;&|()<>\\x60-]|[\"'\\x60]?\\s*($|[;&|\\n)])))",
		"(?i)\\bRemove-Item\\b.*-r\\w*.*-f\\w*",
		"(?i)\\bRemove-Item\\b.*-f\\w*.*-r\\w*",
		"(?i)Format-Volume",
		"(?i)Clear-Disk",
		"(?i)Stop-Computer",
		"(?i)Restart-Computer",
		"(?i)\\b(Invoke-WebRequest|iwr|irm|Invoke-RestMethod|curl|wget)\\b[^|]*\\|\\s*(Invoke-Expression|iex)\\b",
		"(?i)\\b(Invoke-WebRequest|iwr|irm|Invoke-RestMethod|curl|wget)\\b[^;]*;[^;]*\\b(Invoke-Expression|iex)\\b",
		"(?i)\\b(Set-Content|Clear-Content|Out-File|Add-Content)\\b[^|]*\\b(Windows\\\\System32|\\\\Windows\\\\|\\\\etc\\\\|\\\\boot)",
		"(?i)\\bSet-ItemProperty\\b[^|]*HKLM",
		"(?i)\\b(Register-ScheduledTask|schtasks\\s+/create)\\b",
		"(?i)Set-ExecutionPolicy",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(mv|checkout|switch|restore)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(update-index|read-tree|checkout-index|mergetool|difftool|hook)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+add(\\s*($|[;&|)\\n])|\\s+(-[^\\s-]*[a-mo-uw-z]|--(all|update|patch|interactive|force|edit|intent-to-add|chmod|renormalize|refresh|sparse|ignore-missing|ignore-removal|pathspec-from-file)\\b|--\\s|[^\\s;&|<>()\\x60-]))",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+rm(\\s*($|[;&|)\\n])|\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(-[^\\s-]*[frRF]|--(cached|force|recursive|ignore-unmatch|pathspec-from-file)\\b|--\\s|[^\\s;&|<>()\\x60-]))",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+clean\\s+(?:(?:[^\\s;&|()-][^\\s;&|()]*|-[^\\sn-][^\\sn]*|--(?:exclude|quiet|verbose)\\b(?:=[^\\s;&|()]+|\\s+[^\\s;&|()]+)?)\\s+)*(-[^\\s-]*[dDfFxXiI]|--(force|directory|interactive)\\b)",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+stash(\\s*($|[;&|)\\n])|\\s+(push|pop|apply|drop|clear|store|branch|create|save)\\b|\\s+-)",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+apply(\\s*($|[;&|)\\n])|\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(-[^\\s-]*[3R]|--(cached|index|3way|reverse|whitespace|exclude|include|directory|recount|build-fake-ancestor|allow-empty|inaccurate-eof|unsafe-paths|binary)\\b|--\\s|[^\\s;&|()\\x60-]))",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(commit|am|merge|rebase|revert|cherry-pick|replace|update-ref|symbolic-ref|bisect|filter-branch|filter-repo|fast-import)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+reset\\s+(-[^\\s-]+|--(hard|soft|mixed|keep|merge|patch|quiet|interactive|pathspec-from-file)\\b|\\S*[~^/]|[^;&|()]*\\s--(hard|soft|mixed|keep|merge|patch|quiet|interactive)\\b|[^\\s;&|<>()\\x60-]+[\"'\\x60]?\\s*($|[;&|\\n)]))",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+config\\s+((?:--[^\\s]+|--|-[fF]\\s+\\S+)\\s+)*(-[eE]\\b|--(unset(-all)?|add|replace-all|rename-section|remove-section|edit)\\b|[^-\\s]\\S*\\s+\\S)",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+notes\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose|--ref(=[^\\s]+|\\s+[^-\\s]\\S*)?)\\s+)*(add|append|copy|edit|prune|remove|merge)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+reflog\\s+(expire|delete)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+branch\\s+(-[^\\s-]*[dDfFmMcCtuU]|--(delete|move|copy|edit-description|set-upstream-to|unset-upstream|track|force|create-reflog)\\b|--\\s|[^\\s;&|<>()\\x60-])",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+tag\\s+(-[^\\s-]*[aAdDfFmsSuU]|--(delete|force|annotate|sign|local-user|edit|create-reflog)\\b|--\\s|[^\\s;&|<>()\\x60-])",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+remote\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(add|remove|rm|rename|set-url|set-head|set-branches|prune|update)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+submodule\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(add|init|deinit|update|set-url|set-branch|sync|absorbgitdirs|foreach)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+worktree\\s+((?:-[^\\s-]*[qv]|--quiet|--verbose)\\s+)*(add|remove|prune|move|repair|lock|unlock)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+sparse-checkout\\s+(set|add|reapply|disable|init|cone|no-cone)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(clone|push|pull|send-email|imap-send|daemon|instaweb)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+bundle\\s+create\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(send-pack|upload-pack|receive-pack|shell|http-backend|upload-archive|http-push)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+(init|gc|prune|maintenance|repack|pack-refs|pack-objects|update-server-info|multi-pack-index|for-each-repo|hash-object|write-tree|mktree|mktag|unpack-objects|index-pack|credential|rerere|backfill|p4|svn|lfs)\\b",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+archive\\s+[^;&|()]*\\s?(-o\\S*|--output\\S*)",
		"(?i)(^|[\\s;&|(\\x60]|[/\\\\])git(\\.exe)?(?:\\s+(?:-[cC](?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|-[pP]|--(?:git-dir|work-tree|namespace|exec-path|config-env|attr-source|list-cmds)(?:[=\\s]*(?:\"[^\"]*\"|'[^']*'|\\\\[\\s\\S]|[^\\s\"'])+)?|--(?:bare|no-replace-objects|no-lazy-fetch|no-optional-locks|no-advice|paginate|no-pager|literal-pathspecs|glob-pathspecs|noglob-pathspecs|icase-pathspecs)\\b))*\\s+format-patch\\s+[^;&|()]*\\s?(-o\\S*|--output\\S*)",
	}
}

// migrateLegacyGroupBlacklists performs the one-time load migration from the
// pre-rename `blacklist` yaml key to `blocklist`. It runs right after yaml
// decoding, before ApplyDefaults and validate:
//
//   - a legacy blacklist on the execute group that DIFFERS from the shipped
//     legacy default (legacyDefaultExecuteGroupBlacklist) is moved into
//     Blocklist — the user customized the list, so the customization
//     survives; the next Save persists it under the new `blocklist` key;
//   - a legacy blacklist equal to the legacy default, or absent (nil), is
//     dropped: the effective blocklist is empty either way, and keeping the
//     stale patterns pinned in config.yaml would defeat the removal of the
//     predefined list;
//   - a legacy blacklist on any other group is dropped (it was rejected by
//     validation before the rename anyway);
//   - an explicit `blocklist` key always wins: when both keys are present
//     the legacy value is discarded without overwriting it.
//
// The legacy field is cleared unconditionally so the stale `blacklist` key
// disappears from the file at the next Save.
func migrateLegacyGroupBlacklists(groups map[string]GroupPolicyConfig) {
	for name, group := range groups {
		if group.LegacyBlacklist == nil {
			continue
		}
		legacy := group.LegacyBlacklist
		group.LegacyBlacklist = nil
		if name == ToolGroupExecute &&
			group.Blocklist == nil &&
			!samePatternSet(legacy, legacyDefaultExecuteGroupBlacklist()) {
			group.Blocklist = legacy
		}
		groups[name] = group
	}
}

// samePatternSet reports whether two pattern lists hold the same entries
// regardless of order. The legacy default is compared against the stored list
// only to tell "user customized the list" apart from "the shipped default is
// still in effect": regex-list order does not change which patterns match, so
// a reordered list is still the default and must be dropped rather than
// carried over. Sorted copies keep the comparison exact for multisets — an
// added, removed or duplicated pattern still counts as a customization.
func samePatternSet(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	as := slices.Clone(a)
	bs := slices.Clone(b)
	slices.Sort(as)
	slices.Sort(bs)
	return slices.Equal(as, bs)
}
