// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveSession(arg1) {
  return window['go']['desktop']['App']['ArchiveSession'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['desktop']['App']['CancelTask'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['desktop']['App']['CreateProject'](arg1, arg2);
}

export function CreateSession() {
  return window['go']['desktop']['App']['CreateSession']();
}

export function DeleteProject(arg1) {
  return window['go']['desktop']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['desktop']['App']['DeleteSession'](arg1);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetLogLevel() {
  return window['go']['desktop']['App']['GetLogLevel']();
}

export function GetSecuritySettings() {
  return window['go']['desktop']['App']['GetSecuritySettings']();
}

export function GetSessionHistory(arg1) {
  return window['go']['desktop']['App']['GetSessionHistory'](arg1);
}

export function GetSessionTokens(arg1) {
  return window['go']['desktop']['App']['GetSessionTokens'](arg1);
}

export function GetSessionWorkspace(arg1) {
  return window['go']['desktop']['App']['GetSessionWorkspace'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['desktop']['App']['ListDirectory'](arg1);
}

export function ListProjects() {
  return window['go']['desktop']['App']['ListProjects']();
}

export function ListProviderModels(arg1) {
  return window['go']['desktop']['App']['ListProviderModels'](arg1);
}

export function ListSessions() {
  return window['go']['desktop']['App']['ListSessions']();
}

export function PickDirectory() {
  return window['go']['desktop']['App']['PickDirectory']();
}

export function RenameProject(arg1, arg2) {
  return window['go']['desktop']['App']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['desktop']['App']['RenameSession'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['desktop']['App']['SendMessage'](arg1, arg2);
}

export function SetLogLevel(arg1) {
  return window['go']['desktop']['App']['SetLogLevel'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['desktop']['App']['SetTheme'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['desktop']['App']['SwitchProject'](arg1);
}

export function UnwatchDirectory(arg1) {
  return window['go']['desktop']['App']['UnwatchDirectory'](arg1);
}

export function UpdateLLMSettings(arg1) {
  return window['go']['desktop']['App']['UpdateLLMSettings'](arg1);
}

export function UpdateSearchSettings(arg1) {
  return window['go']['desktop']['App']['UpdateSearchSettings'](arg1);
}

export function UpdateSecuritySettings(arg1) {
  return window['go']['desktop']['App']['UpdateSecuritySettings'](arg1);
}

export function UpdateSessionTokens(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['UpdateSessionTokens'](arg1, arg2, arg3);
}

export function WatchDirectory(arg1) {
  return window['go']['desktop']['App']['WatchDirectory'](arg1);
}
