// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {session} from '../models';
import {backend} from '../models';
import {workspace} from '../models';
import {config} from '../models';
import {mcp} from '../models';
import {desktop} from '../models';

export function ApprovePlan(arg1:string,arg2:string):Promise<void>;

export function ArchiveSession(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CancelUnfinishedTask(arg1:string):Promise<void>;

export function Commit(arg1:string):Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<project.ProjectInfo>;

export function CreateSession():Promise<session.SessionInfo>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetBlackboardState(arg1:string):Promise<backend.BlackboardStateResponse>;

export function GetBranches():Promise<Array<workspace.Branch>>;

export function GetConfig():Promise<backend.ConfigResponse>;

export function GetCurrentBranch():Promise<string>;

export function GetDiffStat(arg1:string):Promise<workspace.DiffStat>;

export function GetFileDiff(arg1:string):Promise<string>;

export function GetFileIcon(arg1:string):Promise<backend.FileIconResponse>;

export function GetGitStatus(arg1:string):Promise<Record<string, workspace.GitStatusEntry>>;

export function GetLogLevel():Promise<string>;

export function GetMCPServers():Promise<Record<string, config.MCPServerConfig>>;

export function GetMCPStatus():Promise<Array<mcp.ServerStatus>>;

export function GetProjectSwitchState(arg1:string):Promise<backend.ProjectUIStateResponse>;

export function GetProjectUIState(arg1:string):Promise<backend.ProjectUIStateResponse>;

export function GetProxySettings():Promise<backend.ProxySettingsResponse>;

export function GetSecuritySettings():Promise<backend.SecuritySettingsResponse>;

export function GetSessionHistory(arg1:string):Promise<Array<session.ChatMessage>>;

export function GetSessionTokens(arg1:string):Promise<backend.SessionTokensResponse>;

export function GetSessionWorkspace(arg1:string):Promise<string>;

export function GetTerminalHistory(arg1:string):Promise<Array<session.TerminalCommand>>;

export function GetToolList():Promise<Array<backend.ToolInfo>>;

export function GetVectorIndexStatus():Promise<backend.VectorIndexStatus>;

export function Lifecycle():Promise<backend.FrontendAPILifecycle>;

export function ListDirectory(arg1:string,arg2:boolean):Promise<Array<workspace.FileNode>>;

export function ListProjects():Promise<Array<project.ProjectInfo>>;

export function ListProviderModels(arg1:string):Promise<Array<string>>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function ListSkills():Promise<Array<backend.SkillDescriptorDTO>>;

export function OptimizePrompt(arg1:string):Promise<backend.OptimizePromptResponse>;

export function PickDirectory():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function RejectPlan(arg1:string,arg2:string):Promise<void>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function SaveProjectSwitchState(arg1:backend.ProjectUIStateRequest):Promise<void>;

export function SaveProjectUIState(arg1:backend.ProjectUIStateRequest):Promise<void>;

export function SearchVectorStore(arg1:backend.SearchRequest):Promise<Array<backend.VectorStoreEntry>>;

export function SendMessage(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetWailsLogger(arg1:desktop.wailsLogAdapter):Promise<void>;

export function StageAll():Promise<void>;

export function StageFile(arg1:string):Promise<void>;

export function StartTerminal(arg1:string):Promise<void>;

export function StopTerminal(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function UnstageAll():Promise<void>;

export function UnstageFile(arg1:string):Promise<void>;

export function UnwatchDirectory(arg1:string):Promise<void>;

export function UpdateLLMConfig(arg1:backend.LLMFullConfigRequest):Promise<void>;

export function UpdateMCPServers(arg1:Record<string, config.MCPServerConfig>):Promise<void>;

export function UpdateProxySettings(arg1:backend.ProxySettingsRequest):Promise<void>;

export function UpdateSearchSettings(arg1:backend.SearchSettingsRequest):Promise<void>;

export function UpdateSecuritySettings(arg1:backend.SecuritySettingsResponse):Promise<void>;

export function WatchDirectory(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
