// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortMerge() {
  return window['go']['desktop']['App']['AbortMerge']();
}

export function AbortRebase() {
  return window['go']['desktop']['App']['AbortRebase']();
}

export function AppendToGitignore(arg1) {
  return window['go']['desktop']['App']['AppendToGitignore'](arg1);
}

export function ArchiveSession(arg1) {
  return window['go']['desktop']['App']['ArchiveSession'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['desktop']['App']['CancelTask'](arg1);
}

export function CancelUnfinishedTask(arg1) {
  return window['go']['desktop']['App']['CancelUnfinishedTask'](arg1);
}

export function CheckoutBranch(arg1) {
  return window['go']['desktop']['App']['CheckoutBranch'](arg1);
}

export function Commit(arg1) {
  return window['go']['desktop']['App']['Commit'](arg1);
}

export function CreateBranch(arg1) {
  return window['go']['desktop']['App']['CreateBranch'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['desktop']['App']['CreateProject'](arg1, arg2);
}

export function CreateSession() {
  return window['go']['desktop']['App']['CreateSession']();
}

export function DeleteProject(arg1) {
  return window['go']['desktop']['App']['DeleteProject'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['desktop']['App']['DeleteSession'](arg1);
}

export function DiscardChanges(arg1) {
  return window['go']['desktop']['App']['DiscardChanges'](arg1);
}

export function EmitSessionEvent(arg1) {
  return window['go']['desktop']['App']['EmitSessionEvent'](arg1);
}

export function Fetch(arg1) {
  return window['go']['desktop']['App']['Fetch'](arg1);
}

export function GenerateCommitMessage() {
  return window['go']['desktop']['App']['GenerateCommitMessage']();
}

export function GetBlackboardState(arg1) {
  return window['go']['desktop']['App']['GetBlackboardState'](arg1);
}

export function GetBranches() {
  return window['go']['desktop']['App']['GetBranches']();
}

export function GetCommitFiles(arg1) {
  return window['go']['desktop']['App']['GetCommitFiles'](arg1);
}

export function GetCommitLog(arg1, arg2) {
  return window['go']['desktop']['App']['GetCommitLog'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['desktop']['App']['GetConfig']();
}

export function GetCurrentBranch() {
  return window['go']['desktop']['App']['GetCurrentBranch']();
}

export function GetDiffStat(arg1) {
  return window['go']['desktop']['App']['GetDiffStat'](arg1);
}

export function GetDiffStats() {
  return window['go']['desktop']['App']['GetDiffStats']();
}

export function GetFileDiff(arg1) {
  return window['go']['desktop']['App']['GetFileDiff'](arg1);
}

export function GetFileIcon(arg1) {
  return window['go']['desktop']['App']['GetFileIcon'](arg1);
}

export function GetGitGraph(arg1, arg2) {
  return window['go']['desktop']['App']['GetGitGraph'](arg1, arg2);
}

export function GetGitStatus(arg1) {
  return window['go']['desktop']['App']['GetGitStatus'](arg1);
}

export function GetLogLevel() {
  return window['go']['desktop']['App']['GetLogLevel']();
}

export function GetMCPServers() {
  return window['go']['desktop']['App']['GetMCPServers']();
}

export function GetMCPStatus() {
  return window['go']['desktop']['App']['GetMCPStatus']();
}

export function GetPendingActions(arg1) {
  return window['go']['desktop']['App']['GetPendingActions'](arg1);
}

export function GetProjectSwitchState(arg1) {
  return window['go']['desktop']['App']['GetProjectSwitchState'](arg1);
}

export function GetProjectUIState(arg1) {
  return window['go']['desktop']['App']['GetProjectUIState'](arg1);
}

export function GetProxySettings() {
  return window['go']['desktop']['App']['GetProxySettings']();
}

export function GetRebaseMergeState() {
  return window['go']['desktop']['App']['GetRebaseMergeState']();
}

export function GetSecuritySettings() {
  return window['go']['desktop']['App']['GetSecuritySettings']();
}

export function GetSessionHistory(arg1) {
  return window['go']['desktop']['App']['GetSessionHistory'](arg1);
}

export function GetSessionRuntimeStatus(arg1) {
  return window['go']['desktop']['App']['GetSessionRuntimeStatus'](arg1);
}

export function GetSessionTokens(arg1) {
  return window['go']['desktop']['App']['GetSessionTokens'](arg1);
}

export function GetSessionWorkspace(arg1) {
  return window['go']['desktop']['App']['GetSessionWorkspace'](arg1);
}

export function GetTerminalHistory(arg1) {
  return window['go']['desktop']['App']['GetTerminalHistory'](arg1);
}

export function GetToolList() {
  return window['go']['desktop']['App']['GetToolList']();
}

export function GetVectorIndexStatus() {
  return window['go']['desktop']['App']['GetVectorIndexStatus']();
}

export function Lifecycle() {
  return window['go']['desktop']['App']['Lifecycle']();
}

export function ListDirectory(arg1, arg2) {
  return window['go']['desktop']['App']['ListDirectory'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['desktop']['App']['ListProjects']();
}

export function ListProviderModels(arg1) {
  return window['go']['desktop']['App']['ListProviderModels'](arg1);
}

export function ListSessions() {
  return window['go']['desktop']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['desktop']['App']['ListSkills']();
}

export function Merge(arg1) {
  return window['go']['desktop']['App']['Merge'](arg1);
}

export function OptimizePrompt(arg1) {
  return window['go']['desktop']['App']['OptimizePrompt'](arg1);
}

export function PickDirectory() {
  return window['go']['desktop']['App']['PickDirectory']();
}

export function Pull(arg1) {
  return window['go']['desktop']['App']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['desktop']['App']['Push'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['desktop']['App']['ReadFile'](arg1);
}

export function Rebase(arg1) {
  return window['go']['desktop']['App']['Rebase'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['desktop']['App']['RenameProject'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['desktop']['App']['RenameSession'](arg1, arg2);
}

export function ResolvePendingMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['ResolvePendingMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function ResumeTask(arg1) {
  return window['go']['desktop']['App']['ResumeTask'](arg1);
}

export function SaveProjectSwitchState(arg1) {
  return window['go']['desktop']['App']['SaveProjectSwitchState'](arg1);
}

export function SaveProjectUIState(arg1) {
  return window['go']['desktop']['App']['SaveProjectUIState'](arg1);
}

export function SearchVectorStore(arg1) {
  return window['go']['desktop']['App']['SearchVectorStore'](arg1);
}

export function SendMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['desktop']['App']['SendMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function SetLogLevel(arg1) {
  return window['go']['desktop']['App']['SetLogLevel'](arg1);
}

export function SetWailsLogger(arg1) {
  return window['go']['desktop']['App']['SetWailsLogger'](arg1);
}

export function StageAll() {
  return window['go']['desktop']['App']['StageAll']();
}

export function StageFile(arg1) {
  return window['go']['desktop']['App']['StageFile'](arg1);
}

export function StageHunks(arg1, arg2) {
  return window['go']['desktop']['App']['StageHunks'](arg1, arg2);
}

export function StartTerminal(arg1) {
  return window['go']['desktop']['App']['StartTerminal'](arg1);
}

export function StashCreate(arg1) {
  return window['go']['desktop']['App']['StashCreate'](arg1);
}

export function StashDrop(arg1) {
  return window['go']['desktop']['App']['StashDrop'](arg1);
}

export function StashList() {
  return window['go']['desktop']['App']['StashList']();
}

export function StashPop(arg1) {
  return window['go']['desktop']['App']['StashPop'](arg1);
}

export function StopTerminal(arg1) {
  return window['go']['desktop']['App']['StopTerminal'](arg1);
}

export function SwitchProject(arg1) {
  return window['go']['desktop']['App']['SwitchProject'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['desktop']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['TerminalResize'](arg1, arg2, arg3);
}

export function UnstageAll() {
  return window['go']['desktop']['App']['UnstageAll']();
}

export function UnstageFile(arg1) {
  return window['go']['desktop']['App']['UnstageFile'](arg1);
}

export function UnwatchDirectory(arg1) {
  return window['go']['desktop']['App']['UnwatchDirectory'](arg1);
}

export function UpdateLLMConfig(arg1) {
  return window['go']['desktop']['App']['UpdateLLMConfig'](arg1);
}

export function UpdateMCPServers(arg1) {
  return window['go']['desktop']['App']['UpdateMCPServers'](arg1);
}

export function UpdateProxySettings(arg1) {
  return window['go']['desktop']['App']['UpdateProxySettings'](arg1);
}

export function UpdateSearchSettings(arg1) {
  return window['go']['desktop']['App']['UpdateSearchSettings'](arg1);
}

export function UpdateSecuritySettings(arg1) {
  return window['go']['desktop']['App']['UpdateSecuritySettings'](arg1);
}

export function WatchDirectory(arg1) {
  return window['go']['desktop']['App']['WatchDirectory'](arg1);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['desktop']['App']['WriteFile'](arg1, arg2, arg3);
}
