// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {rtk} from '../models';
import {project} from '../models';
import {session} from '../models';
import {desktop} from '../models';
import {config} from '../models';

export function ArchiveSession(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CheckCodebaseMemoryMCP():Promise<mcp.CodeMemoryStatus>;

export function CheckRtk():Promise<rtk.RtkStatus>;

export function CreateProject(arg1:string,arg2:string):Promise<project.ProjectInfo>;

export function CreateSession():Promise<session.SessionInfo>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<desktop.ConfigResponse>;

export function GetLogLevel():Promise<string>;

export function GetMCPServers():Promise<Record<string, config.MCPServerConfig>>;

export function GetMCPStatus():Promise<Array<mcp.ServerStatus>>;

export function GetSecuritySettings():Promise<desktop.SecuritySettingsResponse>;

export function GetSessionHistory(arg1:string):Promise<Array<session.ChatMessage>>;

export function GetSessionTokens(arg1:string):Promise<desktop.SessionTokensResponse>;

export function GetSessionWorkspace(arg1:string):Promise<string>;

export function GetToolList():Promise<Array<desktop.ToolInfo>>;

export function InstallCodebaseMemoryMCP():Promise<void>;

export function InstallRtk():Promise<void>;

export function ListDirectory(arg1:string):Promise<Array<desktop.FileNode>>;

export function ListProjects():Promise<Array<project.ProjectInfo>>;

export function ListProviderModels(arg1:string):Promise<Array<string>>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function PickDirectory():Promise<string>;

export function RenameProject(arg1:string,arg2:string):Promise<void>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function ResumeTask(arg1:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SwitchProject(arg1:string):Promise<void>;

export function UnwatchDirectory(arg1:string):Promise<void>;

export function UpdateLLMSettings(arg1:desktop.LLMSettingsRequest):Promise<void>;

export function UpdateMCPServers(arg1:Record<string, config.MCPServerConfig>):Promise<void>;

export function UpdateSearchSettings(arg1:desktop.SearchSettingsRequest):Promise<void>;

export function UpdateSecuritySettings(arg1:desktop.SecuritySettingsResponse):Promise<void>;

export function UpdateSessionTokens(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WatchDirectory(arg1:string):Promise<void>;
