package toolmanager

import (
	_ "embed" // for //go:embed markitdown_lock.txt
	"log/slog"
	"path"
)

// markitdownLock is the fully pinned, universal requirements lock for the
// markitdown[all]==0.1.4 dependency tree, generated by
//
//	uv pip compile --universal --python-version 3.12 \
//	  markitdown_requirements.in -o markitdown_lock.txt
//
// and verified against OSV (0 known vulnerabilities). Installing from this
// lock instead of the floating "markitdown[all]==0.1.4" spec pins every
// transitive dependency at exactly the audited versions.
//
//go:embed markitdown_lock.txt
var markitdownLock string

// ToolType classifies how a managed tool is installed and invoked.
type ToolType string

const (
	// StaticBinary is a self-contained executable downloaded as an archive.
	StaticBinary ToolType = "static_binary"
	// PythonPackage is a pip-installable package requiring a Python runtime.
	PythonPackage ToolType = "python_package"
)

// ToolSpec describes a managed external tool, including per-platform
// download URLs, checksums, and archive layout.
type ToolSpec struct {
	Name        string // unique name, e.g. "rg", "uv", "markitdown"
	Version     string // pinned upstream version
	Type        ToolType
	Description string
	BinName     string // executable name after install, e.g. "rg"

	// ArchiveName returns the archive file name for the current platform
	// (e.g. "ripgrep-14.1.1-x86_64-apple-darwin.tar.gz").
	// Constructed from PlatformTriple() unless ArchiveNameOverride is set.
	ArchiveName string

	// ArchiveNameOverride, when non-empty, replaces the PlatformTriple-derived
	// ArchiveName. Use this when an upstream project uses a different naming
	// convention than PlatformTriple for a specific platform (e.g. uv uses
	// "-gnu" on linux-amd64, but PlatformTriple returns "-musl").
	ArchiveNameOverride string

	// BinPathInArchive is the relative path to the binary inside the archive
	// (e.g. "ripgrep-14.1.1-x86_64-apple-darwin/rg").
	// Constructed from PlatformTriple() unless BinPathInArchiveOverride is set.
	BinPathInArchive string

	// BinPathInArchiveOverride, when non-empty, replaces the PlatformTriple-derived
	// BinPathInArchive. See ArchiveNameOverride for rationale.
	BinPathInArchiveOverride string

	// PipSpec is the pip install spec for PythonPackage tools (e.g. "markitdown[all]").
	// Used only as a fallback when RequirementsLock is empty.
	PipSpec string

	// RequirementsLock is the full pinned requirements lock (the content of a
	// uv-generated lock file) for PythonPackage tools. When non-empty,
	// InstallPythonPackage materializes it as <toolsDir>/<name>-lock.txt and
	// installs with `uv pip install -r <lock>`, pinning every transitive
	// dependency at exactly the audited versions. When empty, the installer
	// falls back to the floating PipSpec.
	RequirementsLock string

	// PythonVersion is the Python version required for PythonPackage tools.
	PythonVersion string

	// URLs maps platform keys to download URLs.
	URLs map[string]string

	// Checksums maps platform keys to SHA256 hex strings. A missing/empty
	// checksum fails verification (fail-closed, ASI04-R2); every supported
	// platform MUST declare one.
	Checksums map[string]string
}

// ManagedTools returns the registry of all tools managed by the tool-manager
// in dependency order: uv first (needed to bootstrap markitdown), then static
// binary (rg), then markitdown last.
//
// Note: markitdown is infrastructure-only at this stage — the
// tool-manager downloads and installs it, but no built-in tool wrapper
// consumes it yet. Wrappers will be added in github.com/v0lka/sp4rk/tools/builtins/ when the
// agent is ready to invoke it.
func ManagedTools(logger *slog.Logger) ([]ToolSpec, error) {
	triple := PlatformTriple(logger)
	tools := []ToolSpec{
		{
			Name:             "uv",
			Version:          "0.12.1",
			Type:             StaticBinary,
			Description:      "Python package and project manager (bootstrapper for markitdown)",
			BinName:          "uv",
			ArchiveName:      "uv-" + triple + ".tar.gz",
			BinPathInArchive: "uv-" + triple + "/uv",
			URLs: map[string]string{
				"darwin-amd64":  "https://github.com/astral-sh/uv/releases/download/0.12.1/uv-x86_64-apple-darwin.tar.gz",
				"darwin-arm64":  "https://github.com/astral-sh/uv/releases/download/0.12.1/uv-aarch64-apple-darwin.tar.gz",
				"linux-amd64":   "https://github.com/astral-sh/uv/releases/download/0.12.1/uv-x86_64-unknown-linux-musl.tar.gz",
				"linux-arm64":   "https://github.com/astral-sh/uv/releases/download/0.12.1/uv-aarch64-unknown-linux-gnu.tar.gz",
				"windows-amd64": "https://github.com/astral-sh/uv/releases/download/0.12.1/uv-x86_64-pc-windows-msvc.zip",
			},
			Checksums: map[string]string{
				"darwin-amd64":  "69d9f9a00337f25a50dcb13882052da08b8469bac11091c98c5694c3c6721467",
				"darwin-arm64":  "77d2906988e8074fd43f2f329ec452ebbf9b0c257ba1c66451c71de70a6baf42",
				"linux-amd64":   "47823f814693bab8623308341369190de30b5c621eec5b1ee20352eae8c7982c",
				"linux-arm64":   "769d373e146692c639b5fbaae33b331c297a32e03d30448772051902df52bbf4",
				"windows-amd64": "8fcb0cb46e1229065e344758980924e569bef5882ef45f46fada8fb24e06b74a",
			},
		},
		{
			Name:             "rg",
			Version:          "14.1.1",
			Type:             StaticBinary,
			Description:      "Fast recursive regex content search (ripgrep)",
			BinName:          "rg",
			ArchiveName:      "ripgrep-14.1.1-" + triple + ".tar.gz",
			BinPathInArchive: "ripgrep-14.1.1-" + triple + "/rg",
			URLs: map[string]string{
				"darwin-amd64":  "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-apple-darwin.tar.gz",
				"darwin-arm64":  "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-aarch64-apple-darwin.tar.gz",
				"linux-amd64":   "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz",
				"linux-arm64":   "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-aarch64-unknown-linux-gnu.tar.gz",
				"windows-amd64": "https://github.com/BurntSushi/ripgrep/releases/download/14.1.1/ripgrep-14.1.1-x86_64-pc-windows-msvc.zip",
			},
			Checksums: map[string]string{
				"darwin-amd64":  "fc87e78f7cb3fea12d69072e7ef3b21509754717b746368fd40d88963630e2b3",
				"darwin-arm64":  "24ad76777745fbff131c8fbc466742b011f925bfa4fffa2ded6def23b5b937be",
				"linux-amd64":   "4cf9f2741e6c465ffdb7c26f38056a59e2a2544b51f7cc128ef28337eeae4d8e",
				"linux-arm64":   "c827481c4ff4ea10c9dc7a4022c8de5db34a5737cb74484d62eb94a95841ab2f",
				"windows-amd64": "d0f534024c42afd6cb4d38907c25cd2b249b79bbe6cc1dbee8e3e37c2b6e25a1",
			},
		},
		{
			Name:        "markitdown",
			Version:     "0.1.4",
			Type:        PythonPackage,
			Description: "Convert various file formats to Markdown (infrastructure-only: installed via uv but not yet consumed by the agent)",
			BinName:     "markitdown",
			PipSpec:     "markitdown[all]==0.1.4",
			// Fully pinned universal lock (see markitdownLock) — installs the
			// exact audited tree instead of resolving floating transitives.
			RequirementsLock: markitdownLock,
			PythonVersion:    "3.12",
			// PythonPackage tools use uv for bootstrap; URLs/Checksums are nil.
			URLs:      nil,
			Checksums: nil,
		},
	}

	// Apply per-tool overrides for tools whose upstream naming convention
	// differs from PlatformTriple for specific platforms.
	platform := Platform()
	for i := range tools {
		tools[i].ArchiveName = archiveNameForPlatform(tools[i], platform)
		if tools[i].BinPathInArchiveOverride != "" {
			tools[i].BinPathInArchive = tools[i].BinPathInArchiveOverride
		}
	}

	return tools, nil
}

// archiveNameForPlatform resolves the local cache filename for a tool on the
// given platform. The download URL is the source of truth for the archive
// format — upstream ships ".zip" on Windows but ".tar.gz" elsewhere — so
// deriving the name from the URL basename keeps the on-disk extension
// consistent with the actual bytes and lets the installer pick the correct
// extractor. ArchiveNameOverride wins when set; the triple-derived
// ArchiveName is the fallback when there is no URL for the platform.
func archiveNameForPlatform(tool ToolSpec, platform string) string {
	if tool.ArchiveNameOverride != "" {
		return tool.ArchiveNameOverride
	}
	if url, ok := tool.URLs[platform]; ok && url != "" {
		if base := path.Base(url); base != "" && base != "." && base != "/" {
			return base
		}
	}
	return tool.ArchiveName
}
