package llm

import "encoding/json"

// Message — unit of communication with LLM (system/user/assistant/tool).
type Message struct {
	Role       string     `json:"role"`                   // "system" | "user" | "assistant" | "tool"
	Content    string     `json:"content"`                // text content
	ToolCalls  []ToolCall `json:"tool_calls,omitempty"`   // tool calls (for assistant)
	ToolCallID string     `json:"tool_call_id,omitempty"` // call ID (for tool responses)
}

// ToolCall — request to call a tool, generated by LLM.
type ToolCall struct {
	ID    string          `json:"id"`    // unique call ID
	Name  string          `json:"name"`  // tool name
	Input json.RawMessage `json:"input"` // arguments (JSON)
}

// ChatRequest — request to LLM.
type ChatRequest struct {
	Model       string           `json:"model"`
	Messages    []Message        `json:"messages"`
	Tools       []ToolDefinition `json:"tools,omitempty"`
	MaxTokens   int              `json:"max_tokens"`
	Temperature *float64         `json:"temperature,omitempty"` // nil = use provider default
}

// ChatResponse — LLM response.
type ChatResponse struct {
	Message    Message    `json:"message"`
	Usage      TokenUsage `json:"usage"`
	StopReason string     `json:"stop_reason"` // "end_turn" | "tool_use" | "max_tokens"
}

// ChatChunk — streaming response fragment.
type ChatChunk struct {
	Delta      string    `json:"delta"`
	ToolCall   *ToolCall `json:"tool_call,omitempty"`
	StopReason string    `json:"stop_reason,omitempty"`
}

// TokenUsage — token consumption tracking.
type TokenUsage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
}

// ToolDefinition — tool description for LLM (JSON Schema).
type ToolDefinition struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	InputSchema json.RawMessage `json:"input_schema"`
}
