// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {main} from '../models';

export function ArchiveSession(arg1:string):Promise<void>;

export function CancelTask(arg1:string):Promise<void>;

export function CreateSession():Promise<session.SessionInfo>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetConfig():Promise<Record<string, any>>;

export function GetLogLevel():Promise<string>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetSecuritySettings():Promise<main.SecuritySettingsResponse>;

export function GetSessionHistory(arg1:string):Promise<Array<session.ChatMessage>>;

export function GetSessionMemoryStats(arg1:string):Promise<Record<string, any>>;

export function GetSessionTokens(arg1:string):Promise<Record<string, any>>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function UpdateLLMSettings(arg1:main.LLMSettingsRequest):Promise<void>;

export function UpdateMemorySettings(arg1:main.MemorySettingsRequest):Promise<void>;

export function UpdateSearchSettings(arg1:main.SearchSettingsRequest):Promise<void>;

export function UpdateSecuritySettings(arg1:main.SecuritySettingsResponse):Promise<void>;

export function UpdateSessionTokens(arg1:string,arg2:number,arg3:number):Promise<void>;
