// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveSession(arg1) {
  return window['go']['main']['App']['ArchiveSession'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CreateSession() {
  return window['go']['main']['App']['CreateSession']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetSecuritySettings() {
  return window['go']['main']['App']['GetSecuritySettings']();
}

export function GetSessionHistory(arg1) {
  return window['go']['main']['App']['GetSessionHistory'](arg1);
}

export function GetSessionMemoryStats(arg1) {
  return window['go']['main']['App']['GetSessionMemoryStats'](arg1);
}

export function GetSessionTokens(arg1) {
  return window['go']['main']['App']['GetSessionTokens'](arg1);
}

export function ListProviderModels(arg1) {
  return window['go']['main']['App']['ListProviderModels'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['main']['App']['RenameSession'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function UpdateLLMSettings(arg1) {
  return window['go']['main']['App']['UpdateLLMSettings'](arg1);
}

export function UpdateMemorySettings(arg1) {
  return window['go']['main']['App']['UpdateMemorySettings'](arg1);
}

export function UpdateSearchSettings(arg1) {
  return window['go']['main']['App']['UpdateSearchSettings'](arg1);
}

export function UpdateSecuritySettings(arg1) {
  return window['go']['main']['App']['UpdateSecuritySettings'](arg1);
}

export function UpdateSessionTokens(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSessionTokens'](arg1, arg2, arg3);
}
